name: Build swig

on:
  push:
    branches: 
      - '**'
    paths:
      - Source/**
      - .github/workflows/**

env:
  BUILD_TYPE: Release

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022, macos-13]
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Show files in build directory
      run: ls build
    - uses: actions/upload-artifact@v4
      with:
        name: swig-${{ matrix.os }}
        path: build
        
